name: Eslint / Prettier, checking formatting / common bugs
on:
  push:
    
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: npm run lint
        
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          node-version: '20.x'
          version: 7.x
      - name: pnpm install
        run: pnpm install
      - name: Format code using prettier
        run: pnpm exec prettier . --write