name: Eslint / Prettier, checking formatting / common bugs
on:
  push:
    
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change working directory
        run: cd TECApp
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: npm run lint
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Check if Prettier could format code
        run: npx prettier --check --no-config .