name: Eslint / Prettier, checking formatting / common bugs
on:
  push:
    
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install pnpm
      - name: pnpm install
        run: pnpm install
      - name: Run ESLint
        run: npm run lint

  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install pnpm
      - name: pnpm install
        run: pnpm install
      - name: Format code using prettier
        run: pnpm exec prettier . --write